FROM devopsfaith/krakend:2.7.0

# CP Plugin
COPY ./plugins/qap-krakend-plugin.so /etc/krakend/plugins/

# CP qapgateway config 
COPY ./qap-gateway.json /etc/krakend/krakend.json

CMD ["run", "-c", "/etc/krakend/krakend.json"]
