name: Deploy KrakenD API Gateway

on:
  push:
    branches:
      - main
    paths:
      - "krakend/krakend.json"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Notifying QAP Admin Api - Starting Login in Docker
        run: |
          curl --location 'https://123c-200-169-13-178.ngrok-free.app/webhook' \
            --header 'Content-Type: application/json' \
            --data '{
              "url": "https://deployment_unit_webhook_key.on.qriarlabs.com",
              "api": "css",
              "deploymentUnit": "deployment_unit_webhook_key",
              "ciStatus": "Init CI"
            }'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Set Image Name
        run: echo "IMAGE_NAME=${{ secrets.REGISTRY_USER }}/${deploymentUnit}:latest" >> $GITHUB_ENV
        env:
          IMAGE_NAME: "${{ secrets.REGISTRY_USER }}/${deploymentUnit}:latest"

      - name: Notifying QAP Admin Api - Webhook for building image docker
        run: |
          curl --location 'https://123c-200-169-13-178.ngrok-free.app/webhook' \
            --header 'Content-Type: application/json' \
            --data '{
              "url": "https://deployment_unit_webhook_key.on.qriarlabs.com",
              "api": "css",
              "deploymentUnit": "deployment_unit_webhook_key",
              "ciStatus": "BUILD_IMAGE_DOCKER"
            }'
      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME -f ./krakend/dockerfile .

      - name: Push Docker Image
        run: docker push $IMAGE_NAME

      - name: Notifying QAP Admin Api - Webhook for docker push
        run: |
          curl --location 'https://123c-200-169-13-178.ngrok-free.app/webhook' \
            --header 'Content-Type: application/json' \
            --data '{
              "url": "https://deployment_unit_webhook_key.on.qriarlabs.com",
              "api": "css",
              "deploymentUnit": "deployment_unit_webhook_key",
              "ciStatus": "IMAGED_BUILT_AND_PUSHED"
            }'

      - name: Deploy to CapRover via Docker Image
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: "${{ secrets.CAPROVER_SERVER }}"
          app: "${{ secrets.KRAKEND_CAPROVER_APP_NAME }}"
          token: "${{ secrets.KRAKEND_CAPROVER_TOKEN }}"
          image: "$IMAGE_NAME"
      - name: Notifying QAP Admin Api - Final
        run: |
          curl --location 'https://123c-200-169-13-178.ngrok-free.app/webhook' \
            --header 'Content-Type: application/json' \
            --data '{
              "url": "https://deployment_unit_webhook_key.on.qriarlabs.com",
              "api": "css",
              "deploymentUnit": "deployment_unit_webhook_key",
              "ciStatus": "DEPLOYED"
            }'