name: Deploy KrakenD, Kong & QAP Gateway

on:
  push:
    branches:
      - main
    paths:
      - "krakend/krakend.json"
      - "kong/**"
      - "qapgateway/**"
      - "qap-gateway/**"

jobs:
  set-flags:
    runs-on: ubuntu-latest
    outputs:
      krakend_enabled: ${{ steps.set-flags.outputs.krakend_enabled }}
      kong_enabled: ${{ steps.set-flags.outputs.kong_enabled }}
      qap_gateway_enabled: ${{ steps.set-flags.outputs.qap_gateway_enabled }}

    steps:
      - name: Notify QAP Admin - Init CI
        run: |
          curl --location 'https://123c-200-169-13-178.ngrok-free.app/webhook' \
            --header 'Content-Type: application/json' \
            --data '{
              "url": "https://deployment_unit_testeqapgw_key.on.qriarlabs.com",
              "api": "css",
              "deploymentUnit": "deployment_unit_testeqapgw_key",
              "ciStatus": "Init CI"
            }'

      - name: Set flags for KrakenD, Kong, and QAP Gateway
        id: set-flags
        run: |
          if [ -n "${{ secrets.KRAKEND_CAPROVER_APP_NAME }}" ]; then
            echo "krakend_enabled=true" >> $GITHUB_OUTPUT
          fi
          if [ -n "${{ secrets.KONG_CAPROVER_APP_NAME }}" ]; then
            echo "kong_enabled=true" >> $GITHUB_OUTPUT
          fi
          if [ -n "${{ secrets.QAP_GATEWAY_CAPROVER_APP_NAME }}" ]; then
            echo "qap_gateway_enabled=true" >> $GITHUB_OUTPUT
          fi

  krakend-deploy:
    needs: set-flags
    if: needs.set-flags.outputs.krakend_enabled == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Set Image Name - KrakenD
        run: echo "IMAGE_NAME=${{ secrets.REGISTRY_USER }}/deployment_unit_testeqapgw_key_krakend:latest" >> $GITHUB_ENV

      - name: Build KrakenD Docker Image
        run: docker build -t $IMAGE_NAME -f ./krakend/dockerfile .

      - name: Push KrakenD Docker Image
        run: docker push $IMAGE_NAME

      - name: Notify QAP Admin - DEPLOYED
        run: |
          curl --location 'https://123c-200-169-13-178.ngrok-free.app/webhook' \
            --header 'Content-Type: application/json' \
            --data '{
              "url": "https://deployment_unit_testeqapgw_key.on.qriarlabs.com",
              "api": "css",
              "deploymentUnit": "deployment_unit_testeqapgw_key",
              "ciStatus": "DEPLOYED"
            }'

  kong-deploy:
    needs: set-flags
    if: needs.set-flags.outputs.kong_enabled == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Set Image Name - Kong
        run: echo "KONG_IMAGE_NAME=${{ secrets.REGISTRY_USER }}/deployment_unit_testeqapgw_key_kong:latest" >> $GITHUB_ENV

      - name: Build Kong Docker Image
        run: docker build -t $KONG_IMAGE_NAME -f ./kong/dockerfile .

      - name: Push Kong Docker Image
        run: docker push $KONG_IMAGE_NAME

      - name: Notify QAP Admin - DEPLOYED
        run: |
          curl --location 'https://123c-200-169-13-178.ngrok-free.app/webhook' \
            --header 'Content-Type: application/json' \
            --data '{
              "url": "https://deployment_unit_testeqapgw_key.on.qriarlabs.com",
              "api": "css",
              "deploymentUnit": "deployment_unit_testeqapgw_key",
              "ciStatus": "DEPLOYED"
            }'

  qap-gateway-deploy:
    needs: set-flags
    if: needs.set-flags.outputs.qap_gateway_enabled == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build QAP Plugin
        run: |
          mkdir -p qap-gateway/plugins
          docker run --rm -v "$(pwd)/qap-gateway:/app" -w /app krakend/builder:2.7.0 \
            go build -buildmode=plugin -o plugins/qap-krakend-plugin.so .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Set Image Name - QAP Gateway
        run: echo "QAP_IMAGE_NAME=${{ secrets.REGISTRY_USER }}/deployment_unit_testeqapgw_key_qap_gateway:latest" >> $GITHUB_ENV

      - name: Build Docker Image - QAP Gateway
        run: docker build -t $QAP_IMAGE_NAME -f ./qap-gateway/dockerfile ./qap-gateway

      - name: Push Docker Image - QAP Gateway
        run: docker push $QAP_IMAGE_NAME

      - name: Notify QAP Admin - DEPLOYED
        run: |
          curl --location 'https://123c-200-169-13-178.ngrok-free.app/webhook' \
            --header 'Content-Type: application/json' \
            --data '{
              "url": "https://deployment_unit_testeqapgw_key.on.qriarlabs.com",
              "api": "css",
              "deploymentUnit": "deployment_unit_testeqapgw_key",
              "ciStatus": "DEPLOYED"
            }'